### ISSUE TITLE
Bug: no-token call gets 200

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#102]
Preconditions: An API created with the gluu-oauth2-client-auth plugin

Step 1: Copy the call from the screenshot (no-token call to the API) 
Step 2: Make the call 
Expected: The response is 401
Actual: The response is 200.

Please look into it as soon as possible.

![2018-05-09_11h45_26](https://user-images.githubusercontent.com/38302725/39791442-12c66c76-537f-11e8-84df-2b8d50bdc05e.png)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
It's fixed when I use the GUI, but when I make a call with no authorization headers, it still gets 200, also for other endpoints. Please take a look: 
![2018-05-11_11h14_17](https://user-images.githubusercontent.com/38302725/39901789-05dc8348-550e-11e8-98e7-7f223b83bc03.png)

![2018-05-11_11h21_47](https://user-images.githubusercontent.com/38302725/39901791-084ea4a8-550e-11e8-83f6-11bd40753803.png)

**Comment by natt-tester** [comment]
Agreed, it's solved. The original API has since been deleted, but any other API with the gluu-oauth2-client-auth plugin will give the same response:
![2018-05-11_11h45_24](https://user-images.githubusercontent.com/38302725/39902354-0011d352-5511-11e8-8102-a44411b20679.png)
