### ISSUE TITLE
Bug: no authorization for https://dev1.gluu.org:1338/#!/settings

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/gluu-gateway#104]
Preconditions: You must be logged out of https://dev1.gluu.org:1338.

Steps:

1. Go to https://dev1.gluu.org:1338
2. Click the LOGIN button
3. Check the login status (logged out)
4. Paste https://dev1.gluu.org:1338/#!/settings into the address bar
5. Click Enter

Expected: The user is redirected to the login screen.
Actual: The user is able to log in to the AP without any authorization -- please refer to the GIF.

![2018-05-09_22h00_29](https://user-images.githubusercontent.com/38302725/39816554-f119d53a-53de-11e8-8ea0-a4ca00d5dfc5.gif)

**Comment by ldeveloperl1985** [comment]
Done

**Comment by natt-tester** [comment]
It's fixed when I use the GUI, but when I make a call with no authorization headers, it still gets 200, also for other endpoints. Please take a look:
![2018-05-11_11h14_17](https://user-images.githubusercontent.com/38302725/39901876-808b7dce-550e-11e8-883d-4e86883e7c94.png)
![2018-05-11_11h21_47](https://user-images.githubusercontent.com/38302725/39901881-830c4fba-550e-11e8-9c8c-19eb33ac0efc.png)

**Comment by ldeveloperl1985** [comment]
Please see the response body. Without authentication, It does not load the original body.
![settingbody](https://user-images.githubusercontent.com/2329776/39914629-389904ae-5523-11e8-859d-8359ddf859c7.png)

**Comment by natt-tester** [comment]
Ok, so it's always redirected to the login page. In this case, the bug is fixed :)
