### ISSUE TITLE
Gluu QA - Unable to add Metrics Plugin

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/gluu-gateway#285]
Version - Gluu Gateway 4.0-58
Platform - "Ubuntu 16.04.5 LTS"

Steps to reproduce:
1. Login to GG
2. Go to Plugins, Add Global Plugin
3. Select Metrics > Gluu Metrics, and click on + sign

Expected: Pop up screen should appear
Actual: Nothing happens

Screenshot
![image](https://user-images.githubusercontent.com/21104811/51614693-3180a200-1f4c-11e9-80bc-6d00c77c80d4.png)

**Comment by ldeveloperl1985** [comment]
Done. @sahiliamsso  @mbaser  Please re-install GG and test

**Comment by mbaser** [comment]
Still having issue. Popup comes but the following error raised
![screenshot_2019-01-24_19-50-42](https://user-images.githubusercontent.com/6398752/51704435-1edc9a80-202a-11e9-8343-f10dee6e97e1.png)

**Comment by ldeveloperl1985** [comment]
@mbaser test it in fresh VM

**Comment by mbaser** [comment]
Tested, it works. Closing this issue.
