### ISSUE TITLE
Unexpected error and redirection 

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway#432]
https://support.gluu.org/outages/8114/invalidate-gluu-gateway-session-when-gluu-server-is-down/#at57977

### Case 1:
step to reproduce: 
ser `max_id_token_age - 1 hour` and `max_id_token_auth_age - 1 min` in OIDC plugin.

After this configuration, GG throwing `unexpected error`.

### Case 2:
`max_id_token_age - 1 min` and `max_id_token_auth_age - 1 min`

After this configuration, GG session out after 1 min. Getting new authorization code from Gluu but GG unable to handle it.

**Comment by ldeveloperl1985** [comment]
I am able to reproduce the first case 1 on test server. @altexy please check the log file.
[error.log](https://github.com/GluuFederation/gluu-gateway/files/4354101/error.log)
[access.log](https://github.com/GluuFederation/gluu-gateway/files/4354102/access.log)

**Comment by altexy** [comment]
I will check this asap

**Comment by altexy** [comment]
Hi @ldeveloperl1985 , I have pushed the branch `432_openidc_unexpected_error`.

During long evolution, my plugin code becomes very difficult to support and was looked as spaghetti code :-(

I have fully refactored the plugin code, encapsulate user session details in the `openid_connect_session_data` Lua class.
IMO the code now is more readable and simpler to understand and support.

Our test suite is passed, but because of big refactoring, we need to make sure that all code works as expected with real oxd/GS.
Can you, please test Case 1 issue above, as well all main scenarios.

BTW the reason for indefinite loop of Case 1 was because GS returns id_token with expired authentication. GG was not able to catch it. Now it is fixed - we cannot do a much here - just responds with 500 and proper message.

**Comment by ldeveloperl1985** [comment]
@altexy  getting error in our test suit
```
Error -> /opt/git/t/specs/gluu-oauth-auth/test_spec.lua @ 271
rate limiter
/opt/git/t/lib/kong_utils.lua:91: postgress container failed to start

Error -> /opt/git/t/specs/gluu-openid-connect/test_spec.lua @ 1325
unexpected error, max_id_token_age - 1 hour and max_id_token_auth_age - 1 min
/opt/git/t/lib/test_utils.lua:50: sh_ex [curl --fail -v -sS -X POST --url http://localhost:33530/register-site --header 'Content-Type: application/json' --data '{"authorization_redirect_uri":"https://client.example.com/cb","client_name":"demo plugin","grant_types":["client_credentials"],"op_host":"just_stub","scope":["openid","uma_protection"]}'] fail

------------------------------------------------------------------

2020/03/31 07:37:32 [error] 6#6: *1 lua entry thread aborted: runtime error: error loading module 'gluu.oxd-model' from file '/usr/local/openresty/lualib/gluu/oxd-model.lua':
	cannot read /usr/local/openresty/lualib/gluu/oxd-model.lua: Is a directory
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:16):2: in main chunk, client: 192.168.224.1, server: , request: "HEAD / HTTP/1.1", host: "127.0.0.1:33530"
2020/03/31 07:37:33 [error] 6#6: *2 lua entry thread aborted: runtime error: error loading module 'gluu.oxd-model' from file '/usr/local/openresty/lualib/gluu/oxd-model.lua':
	cannot read /usr/local/openresty/lualib/gluu/oxd-model.lua: Is a directory
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:16):2: in main chunk, client: 192.168.224.1, server: , request: "POST /register-site HTTP/1.1", host: "localhost:33530"

```

i think you forgot to push `oxd-model9.lua`.

**Comment by altexy** [comment]
@ldeveloperl1985 sorry, fixed, please retake the branch, I have changed the git history

**Comment by ldeveloperl1985** [comment]
@altexy  Facing one issue, could you please take a look?
```
Error -> /opt/git/t/specs/gluu-oauth-auth/test_spec.lua @ 271
rate limiter
/opt/git/t/lib/kong_utils.lua:91: postgress container failed to start
```

**Comment by altexy** [comment]
@ldeveloperl1985 I didn't touch `gluu-oauth-auth` code and tests. It works on my side.
Maybe it is timing issue? It may be on slow laptop.
Is it 100% reproducible?

**Comment by ldeveloperl1985** [comment]
NO, it is seems like my machine problem container issue`: postgress container failed to start`. let me know if you have any workaround on this issue

**Comment by altexy** [comment]
@ldeveloperl1985 try https://gist.github.com/bastman/5b57ddb3c11942094f8d0a97d461b430

**Comment by ldeveloperl1985** [comment]
@altexy I fixed the problem by adding `-e POSTGRES_HOST_AUTH_METHOD=trust` this config in all postgres docker command in our docker suit `kong_util.lua`. because it need password. I have no idea why this is started happening now before somedays it is working well. I think you may reproduce it by deleting postgres image and try with fresh.

**Comment by ldeveloperl1985** [comment]
> Our test suite is passed, but because of big refactoring, we need to make sure that all code works as expected with real oxd/GS.
Can you, please test Case 1 issue above, as well all main scenarios.

@altexy I've tested with our test server and all the things working well

**Comment by altexy** [comment]
> @altexy I fixed the problem by adding `-e POSTGRES_HOST_AUTH_METHOD=trust` this config in all postgres docker command in our docker suit `kong_util.lua`. because it need password. I have no idea why this is started happening now before somedays it is working well. I think you may reproduce it by deleting postgres image and try with fresh.

@ldeveloperl1985 Can you, please, add this to the branch?
Then I will create PR and send it to you for review.

**Comment by altexy** [comment]
> @altexy I've tested with our test server and all the things working well

Great! Thank you very much.

**Comment by ldeveloperl1985** [comment]
> Can you, please, add this to the branch?
Then I will create PR and send it to you for review.

Done @altexy
